# SEOlyzer Configuration

# HTTP settings
http:
  user_agent: "SEOlyzer/1.0 (SEO Analysis Tool)"
  timeout: 30  # seconds
  max_retries: 3
  retry_delay: 5  # seconds

# Proxy settings (optional)
proxy:
  enabled: false
  http: ""
  https: ""

# Crawling settings
crawling:
  max_depth: 2
  max_pages: 100
  respect_robots_txt: true
  delay_between_requests: 1  # seconds

# Performance settings
performance:
  check_core_web_vitals: true
  check_mobile_friendly: true
  check_page_speed: true

# Output settings
output:
  default_format: "json"
  include_timestamp: true
  pretty_print: true 